// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicsEPWbLo8DVFCN4bwrwseW3hUapCtII',
    appId: '1:1031805025906:web:299d82fce5491fb5634ceb',
    messagingSenderId: '1031805025906',
    projectId: 'project-98c9f',
    authDomain: 'project-98c9f.firebaseapp.com',
    storageBucket: 'project-98c9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdudumxGwKeEzXkCrXK02oRupvIGLLUD0',
    appId: '1:1031805025906:android:4652a59681d71ddb634ceb',
    messagingSenderId: '1031805025906',
    projectId: 'project-98c9f',
    storageBucket: 'project-98c9f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCicsEPWbLo8DVFCN4bwrwseW3hUapCtII',
    appId: '1:1031805025906:web:7dffba83e454c028634ceb',
    messagingSenderId: '1031805025906',
    projectId: 'project-98c9f',
    authDomain: 'project-98c9f.firebaseapp.com',
    storageBucket: 'project-98c9f.firebasestorage.app',
  );
}
