name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  intl: ^0.20.2
  hotreloader: ^4.3.0
  fl_chart: ^1.0.0
  cloud_firestore: ^5.6.8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
